INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (1, 0, 7, 'what is up', 'Hey', 1, 0, 0, 1376875936, 0, 1, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (2, 0, 1, 'Hi', 'Queries', 1, 0, 0, 1378969343, 0, 4, 0, 1, 0, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (3, 0, 1, 'There is a small scratch on the upper right side of the left-hand speaker, but', 'Question about the Dynaudios', 1, 0, 0, 1378971133, 0, 4, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (4, 0, 4, 'Hi Just checked your message.', 'How about your query?', 1, 0, 0, 1378987078, 0, 1, 0, 1, 1, 1, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (5, 0, 4, 'Hi Adnan, this is another messages, posted by the admin.', 'Another', 1, 0, 0, 1380977257, 0, 1, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (6, 0, 4, 'Hi Adnan, this is another messages, posted by the admin.', 'Its about AudioFlea', 1, 0, 0, 1380977315, 0, 1, 0, 1, 1, 1, 1);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (7, 0, 4, 'Hi Adnan, this is another messages, posted by the admin.', 'One More', 1, 0, 0, 1380978323, 0, 1, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (8, 0, 4, 'Hi Adnan, this is another messages, posted by the admin. Hi Adnan, this is another messages, posted by the admin. Hi Adnan, this is another messages, posted by the admin.', 'Urgent Query', 1, 0, 0, 1380978358, 0, 1, 0, 1, 1, 0, 1);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (9, 0, 1, 'Reply', 'Request', 1, 0, 0, 1381039020, 0, 4, 0, 1, 1, 0, 1);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (10, 0, 1, 'How is it going?', 'Hey what''s up?', 1, 0, 0, 1384887526, 0, 7, 0, 1, 0, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (11, 0, 1, 'Hey', 'Sup 2', 1, 0, 0, 1384888120, 0, 7, 0, 1, 0, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (12, 0, 1, 'Sup', 'sup 3', 1, 0, 0, 1384888134, 0, 7, 0, 1, 0, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (13, 0, 7, 'Nice looking cartridge!!!', 'RE: Lyra Kleos', 0, 0, 710, 1385240685, 0, 1, 0, 1, 1, 0, 1);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (14, 0, 1, 'Sorry, I just realized I don''t wnt to buy this anymore.  Can you cancel this.  Please do the needful, is urgent.

Cheers.', 'RE: Rega P25', 1, 0, 748, 1387284101, 0, 2, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (15, 0, 2, 'Choke on one', 'RE: Rega P25', 1, 0, 748, 1387292268, 0, 1, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (16, 0, 1, 'Hey Bro!', 'RE: Admin2 7 Jan', 1, 0, 1387, 1389369507, 0, 7, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (17, 0, 7, 'These speakers are junk! I want my money back!!!', 'Test', 1, 0, 0, 1391455174, 0, 30, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (18, 0, 30, 'Ah hell no brah.  work it out with PayPal LOL', 'Hell no', 1, 0, 0, 1391455513, 0, 7, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (19, 0, 7, 'uwotm8 I''ll fukkin wrek u m8', 'Paypal', 1, 0, 0, 1391455654, 0, 30, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (20, 0, 30, 'Will you take a vintage tuner for a trade for these?', 'RE: Wilson Audio Custom Shoe Speakers', 1, 0, 1759, 1391457540, 0, 7, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (21, 0, 7, 'These ain''t your mom''s kicks. No trades.', 'RE: Wilson Audio Custom Shoe Speakers', 1, 0, 1759, 1391457609, 0, 30, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (22, 0, 1, 'I can''t pay.', 'RE: Magnepan 3.7', 1, 0, 6753, 1425742914, 0, 789, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (23, 0, 789, 'OK, my lawyer will be calling', 'RE: Magnepan 3.7', 1, 0, 6753, 1425742969, 0, 1, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (24, 0, 1, 'Do you accept pebble pay?', 'RE: Magnepan 3.7', 1, 0, 6753, 1425743123, 0, 789, 0, 1, 1, 0, 0);
INSERT INTO audioflea_dev.wrd_auction_pm (id, owner, user, content, subject, rd, parent, pid, datemade, readdate, initiator, attached, show_to_source, show_to_destination, is_favorite_destination, is_favorite_source) VALUES (25, 0, 789, 'no, but I do accept wooden nickels', 'RE: Magnepan 3.7', 0, 0, 6753, 1425747706, 0, 1, 0, 1, 1, 0, 0);